name: Run tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: install package and dependencies
        run: pip install -e . && pip install -r test_requirements.txt

      - name: lint code with ruff
        run: ruff check .

      - name: check code format with black
        run: black --check .

      - name: test code with `pytest`
        run: pytest
